const puppeteer = require('puppeteer');
const TestServer = require('./test-server');
const { QemuValidator } = require('./qemu-validator');

/**
 * Validation test that focuses on testing the QEMU commands
 * generated by the application in its current state
 */
class ValidationTestRunner {
  constructor() {
    this.server = new TestServer(3001);
    this.validator = new QemuValidator();
    this.results = {
      total: 0,
      passed: 0,
      failed: 0,
      tests: []
    };
  }

  async runTests() {
    console.log('🔍 CXL Canvas QEMU Validation Tests');
    console.log('===================================\n');

    try {
      await this.server.start();
      
      const browser = await puppeteer.launch({ 
        headless: 'new',
        args: ['--no-sandbox', '--disable-setuid-sandbox']
      });
      const page = await browser.newPage();
      await page.setViewport({ width: 1920, height: 1080 });
      
      await page.goto('http://localhost:3001', { waitUntil: 'networkidle0' });
      await page.waitForSelector('#canvas');
      
      // Test various application states
      await this.testDefaultState(page);
      await this.testRandomTopology(page);
      await this.testAfterReset(page);
      await this.testWithExtraComponents(page);
      
      await browser.close();
      await this.server.stop();
      
      this.printResults();
      return this.results;
      
    } catch (error) {
      console.error('❌ Validation tests failed:', error.message);
      await this.server.stop();
      throw error;
    }
  }

  async testDefaultState(page) {
    console.log('📋 Test 1: Default application state with required CXL memory window');
    
    // Add required CXL fixed memory window to default topology
    await this.ensureMemoryWindowExists(page);
    
    const qemuCommand = await this.getQemuCommand(page);
    const testResult = {
      name: 'Default State with Memory Window',
      qemuCommand,
      validation: this.validator.validateCommand(qemuCommand),
      passed: false,
      notes: []
    };

    this.results.total++;
    
    if (testResult.validation.isValid) {
      testResult.passed = true;
      this.results.passed++;
      console.log('   ✅ PASSED - Default QEMU command is valid');
    } else {
      this.results.failed++;
      console.log('   ❌ FAILED - Default QEMU command has validation errors');
      testResult.validation.errors.forEach(error => {
        console.log(`      - ${error}`);
      });
    }

    // Additional checks
    if (qemuCommand.includes('-M q35,cxl=on')) {
      testResult.notes.push('✓ Correct machine type with CXL enabled');
    }
    
    if (qemuCommand.includes('pxb-cxl')) {
      testResult.notes.push('✓ Contains CXL host bridge');
    }

    // Check for required CXL memory window
    if (qemuCommand.includes('cxl-fixed-memory-window')) {
      testResult.notes.push('✓ Contains required CXL fixed memory window');
    } else {
      testResult.notes.push('❌ Missing required CXL fixed memory window');
      testResult.passed = false;
    }

    this.results.tests.push(testResult);
    console.log('');
  }

  async testRandomTopology(page) {
    console.log('📋 Test 2: Random topology generation with required CXL memory window');
    
    // Generate a random topology
    await page.click('#generate-random');
    await new Promise(resolve => setTimeout(resolve, 2000)); // Wait for generation to complete
    
    // Ensure CXL memory window exists for all topologies
    await this.ensureMemoryWindowExists(page);
    
    const qemuCommand = await this.getQemuCommand(page);
    const testResult = {
      name: 'Random Topology',
      qemuCommand,
      validation: this.validator.validateCommand(qemuCommand),
      passed: false,
      notes: []
    };

    this.results.total++;
    
    if (testResult.validation.isValid) {
      testResult.passed = true;
      this.results.passed++;
      console.log('   ✅ PASSED - Random topology QEMU command is valid');
    } else {
      this.results.failed++;
      console.log('   ❌ FAILED - Random topology QEMU command has validation errors');
      testResult.validation.errors.forEach(error => {
        console.log(`      - ${error}`);
      });
    }

    // Count components in the command
    const deviceCount = (qemuCommand.match(/-device/g) || []).length;
    const objectCount = (qemuCommand.match(/-object/g) || []).length;
    testResult.notes.push(`Contains ${deviceCount} devices and ${objectCount} memory objects`);

    if (qemuCommand.includes('cxl-type3') || qemuCommand.includes('cxl-accel')) {
      testResult.notes.push('✓ Contains CXL endpoint devices');
    }

    // Check for required CXL memory window
    if (qemuCommand.includes('cxl-fixed-memory-window')) {
      testResult.notes.push('✓ Contains required CXL fixed memory window');
    } else {
      testResult.notes.push('❌ Missing required CXL fixed memory window');
      testResult.passed = false;
    }

    this.results.tests.push(testResult);
    console.log('');
  }

  async testAfterReset(page) {
    console.log('📋 Test 3: After reset to default with required CXL memory window');
    
    // Reset to default topology
    await page.click('#reset-canvas');
    await new Promise(resolve => setTimeout(resolve, 1000));
    
    // Add required CXL memory window after reset
    await this.ensureMemoryWindowExists(page);
    
    const qemuCommand = await this.getQemuCommand(page);
    const testResult = {
      name: 'After Reset',
      qemuCommand,
      validation: this.validator.validateCommand(qemuCommand),
      passed: false,
      notes: []
    };

    this.results.total++;
    
    if (testResult.validation.isValid) {
      testResult.passed = true;
      this.results.passed++;
      console.log('   ✅ PASSED - Reset state QEMU command is valid');
    } else {
      this.results.failed++;
      console.log('   ❌ FAILED - Reset state QEMU command has validation errors');
      testResult.validation.errors.forEach(error => {
        console.log(`      - ${error}`);
      });
    }

    testResult.notes.push('Reset returns to basic host-rootport topology with memory window');

    // Check for required CXL memory window
    if (qemuCommand.includes('cxl-fixed-memory-window')) {
      testResult.notes.push('✓ Contains required CXL fixed memory window');
    } else {
      testResult.notes.push('❌ Missing required CXL fixed memory window');
      testResult.passed = false;
    }

    this.results.tests.push(testResult);
    console.log('');
  }

  async testWithExtraComponents(page) {
    console.log('📋 Test 4: Adding unconnected components with required CXL memory window');
    
    // Add some components without connecting them
    await page.click('#add-device');
    await new Promise(resolve => setTimeout(resolve, 500));
    await page.click('#add-switch');
    await new Promise(resolve => setTimeout(resolve, 500));
    await page.click('#add-window');
    await new Promise(resolve => setTimeout(resolve, 1000));
    
    // Ensure the memory window is properly configured
    await this.ensureMemoryWindowExists(page);
    
    const qemuCommand = await this.getQemuCommand(page);
    const testResult = {
      name: 'With Unconnected Components',
      qemuCommand,
      validation: this.validator.validateCommand(qemuCommand),
      passed: false,
      notes: []
    };

    this.results.total++;
    
    if (testResult.validation.isValid) {
      testResult.passed = true;
      this.results.passed++;
      console.log('   ✅ PASSED - Command with unconnected components is valid');
    } else {
      this.results.failed++;
      console.log('   ❌ FAILED - Command with unconnected components has validation errors');
      testResult.validation.errors.forEach(error => {
        console.log(`      - ${error}`);
      });
    }

    // Check for unconnected component comments
    if (qemuCommand.includes('# Unconnected Components')) {
      testResult.notes.push('✓ Properly labels unconnected components');
    }

    if (qemuCommand.includes('cxl-fmw')) {
      testResult.notes.push('✓ Memory window configuration generated');
    }

    // Check for required CXL memory window
    if (qemuCommand.includes('cxl-fixed-memory-window')) {
      testResult.notes.push('✓ Contains required CXL fixed memory window');
    } else {
      testResult.notes.push('❌ Missing required CXL fixed memory window');
      testResult.passed = false;
    }

    this.results.tests.push(testResult);
    console.log('');
  }

  async getQemuCommand(page) {
    return await page.evaluate(() => {
      const commandElement = document.getElementById('qemu-command');
      return commandElement ? commandElement.textContent : '';
    });
  }

  /**
   * Ensures that a CXL fixed memory window exists and is properly associated with host bridges
   * This is a MANDATORY requirement for all valid CXL topologies
   */
  async ensureMemoryWindowExists(page) {
    // Check if a memory window already exists
    const existingWindows = await page.$$('.cxl-component[data-type="window"]');
    
    if (existingWindows.length === 0) {
      console.log('   Adding required CXL fixed memory window...');
      // Add a memory window if none exists
      await page.click('#add-window');
      await new Promise(resolve => setTimeout(resolve, 1000));
    }

    // Configure the memory window to be associated with host bridges
    await this.configureMemoryWindowWithHostBridges(page);
  }

  /**
   * Configures the memory window to be properly associated with one or more host bridges
   */
  async configureMemoryWindowWithHostBridges(page) {
    try {
      // Find and click on the memory window to select it
      const memoryWindows = await page.$$('.cxl-component[data-type="window"]');
      if (memoryWindows.length > 0) {
        await memoryWindows[0].click();
        await new Promise(resolve => setTimeout(resolve, 500));
        
        // Try to check the first available host bridge checkbox
        const hostCheckbox = await page.$('#host-checkboxes input[type="checkbox"]');
        if (hostCheckbox) {
          const isChecked = await page.evaluate(checkbox => checkbox.checked, hostCheckbox);
          if (!isChecked) {
            await hostCheckbox.click();
            await new Promise(resolve => setTimeout(resolve, 200));
            console.log('   ✓ Associated memory window with host bridge');
          }
          
          // Update the component to apply the association
          const updateButton = await page.$('#update-component');
          if (updateButton) {
            await updateButton.click();
            await new Promise(resolve => setTimeout(resolve, 500));
          }
        }
      }
    } catch (error) {
      console.log(`   Note: Could not configure memory window association: ${error.message}`);
    }
  }

  printResults() {
    console.log('📊 Validation Test Summary');
    console.log('==========================');
    console.log(`Total Tests: ${this.results.total}`);
    console.log(`Passed: ${this.results.passed}`);
    console.log(`Failed: ${this.results.failed}`);
    console.log(`Success Rate: ${((this.results.passed / this.results.total) * 100).toFixed(1)}%\n`);

    // Print detailed results
    this.results.tests.forEach(test => {
      console.log(`${test.passed ? '✅' : '❌'} ${test.name}`);
      if (test.notes.length > 0) {
        test.notes.forEach(note => console.log(`   ${note}`));
      }
      if (!test.passed && test.validation.errors.length > 0) {
        console.log('   Validation Errors:');
        test.validation.errors.forEach(error => console.log(`   - ${error}`));
      }
      console.log('');
    });

    console.log(this.results.failed === 0 ? '🎉 All validation tests passed!' : '💥 Some validation tests failed.');
  }
}

// Run if called directly
if (require.main === module) {
  const runner = new ValidationTestRunner();
  runner.runTests()
    .then(results => process.exit(results.failed === 0 ? 0 : 1))
    .catch(() => process.exit(1));
}

module.exports = { ValidationTestRunner };